f=open("file1.txt","w")
f.write("These is first line program\n")
f.write("These is second line program\n")
f.write("These is third line program\n")
f.write("These is fourth line program\n")
f.write("These is fifith line program\n")
f.write("These is sixth line program\n")
f.write("These is seventh line program\n")
f.write("These is eighth line  program\n")
f.write("These is ninth line program\n")
f.write("These is tenth line program\n")
f.write("These is my first file program\n")
f.write("These is my first file program\n")

f.close()