f=open("File.txt",'r')
# list=f.readlines()
# print(list)
# f.close()
# list.reverse()
# print(list)
# f=open("file.txt","w")
# for i in list:
#     f.write(i)
# f.close()
lines=f.read()
print(lines[::-1])
spl=lines.split(" ")
spl=spl[-1::-1]
print(spl)

f.close()
f=open("file.txt","w")
f.write("First line\n")
f.write("Second line\n")
f.write("Third line\n")
f.write("fourth line\n")
f.write("Fivth line")
f.close()