import xlrd
loc = "D:/test.xlsx"
wb = xlrd.open_workbook(loc)
sheet1 = wb.sheet_by_index(0)
print(sheet1.cell_value(0,0))
print(sheet1.cell_value(0,1))
print("--------------------------")
print(sheet1.nrows)
print(sheet1.ncols)
print("--------------------------")
sheet2 = wb.sheet_by_index(1)
print(sheet2.cell_value(0,0))
print(sheet2.cell_value(0,1))
print(sheet2.cell_value(1,0))
print(sheet2.cell_value(1,1))
print("--------------------------")
print(sheet2.automatic_grid_line_colour)
print("--------------------------")
print(sheet2.formatting_info)
print(sheet1.formatting_info)
print("--------------------------")
print(sheet1.default_additional_space_below)
print("--------------------------")
print(sheet1.name)
