#2.Read the input from the user & display the same in the console(employee details)
print("Enter Employee details")
print("-----------------------")
a = input("Enter Employee Name:" )
b = int(input("Enter Employee ID:"))
c= int(input("Enter Employee Salary:"))
print("Employee Name:",a)
print("Emp Id:",b)
print("Emp Sal:",c)