import requests
r = requests.get("https://imgs.xkcd.com/comics/python.png")
print(r)
print(r.status_code)
f = open("D:\confffiiggg\\sample.png","wb")
f.write(r.content)
print(r.content)
f.close()
f = open("D:\confffiiggg\\sample.txt","wb")
f.write(r.content)
print(r.content)
f.close()