import requests
r=requests.get("https://imgs.xkcd.com/comics/python.png")
print(r)
print(r.status_code)
f=open("C:\\Users\\admin\\Desktop\\sample.png","wb")
f.write(r.content)
print(r.content)
f.close()
f=open("C:\\Users\\admin\\Desktop\\sample.txt","wb")
f.write(r.content)
print(r.content)
f.close()