s='Good Morning'
print(s.isdigit())
print(s.isalpha())
print(s.split())
print(s.count('o'))
print(s.count('o',0,2))
print(s.title())
print(s.capitalize())
print(','.join(s))
print(s.replace('Morning','evening'))
print(s.replace('o','h',2))
print("hi {}".format(s))
print(s.index('o'))
print(s.index('M',0,6))
print(s.islower())
'''converts string into lowercase'''
print(s.casefold())
print(s.center(16,'@'))
print(s.find('o',0,5))
print(s.isdecimal())
print(s.isdigit())
s1='**&&&h    ****     i*****'
print(s1.lstrip('*&'))
print(s1.strip('*'))
